### ISSUE TITLE
I2C not Working

### ISSUE THREAD

**Issue by Luchta** [sparkfun/Edison_PWM_Block#3]
I got the following error code after trying to get the sample code to work:

"terminate called after throwing an instance of 'std::invalid_argument'
what(): Unknown error in I2c::readReg()"

I found the Error in the Constructor of pca9685. 
Fabulous Idea to set the prescaler and let it read registers, before setting the address.
changing the order of those two fixed the error.

**Comment by mhord** [comment]
Please provide more information. There's no code at all in this repository, and the constructor for the pca9685 class in the library we wrote for the block doesn't access anything before setting the address. I'm looking at [this repository](https://github.com/sparkfun/SparkFun_PWM_Block_for_Edison_CPP_Library) for the code. Is there a code example elsewhere that doesn't initialize things in the right order?

**Comment by Luchta** [comment]
Hey there,

I am talking about this part:

// Constructor. Pretty self explanatory.
pca9685::pca9685(mraa::I2c* pca_port, uint8_t myI2CAddress):
   _pca_port(pca_port), _myAddress(myI2CAddress),
   _minServoPL(MIN_WIDTH), _maxServoPL(MAX_WIDTH),
   _minAngle(0), _maxAngle(180)
{
   setPrescaler(14); // f= ~400Hz
   _pca_port->address(_myAddress);
   _pca_port->writeReg(MODE1, AI); //enable autoincrement and osc
   _pca_port->writeReg(MODE2, INVRT); // open drain outs
}

the address is written in "_pca_port->address(_myAddress);"

however, "setPrescaler(14);" already accesses the bus and created the 
error I mentioned.

**Comment by mhord** [comment]
Got it. Thanks for the tip!
